spring:
  application:
    name: my-config-server
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: file:///${user.dir}/config-git-repo
          search-paths: "{application}"
#          search-paths: "*"

server:
  port: 8888

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8093/eureka/
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 3
    lease-renewal-interval-in-seconds: 3
logging:
  level:
    org.springframework.cloud.config: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always